### PR TITLE
123103069

### PR DESCRIPTION
**Pull request by RiyaRaj28**
updated review.js

### CODE REVIEW

**Comment by Debatreya** [comment]
@RiyaRaj28 
Did you joined the workshop?

**Comment by Debatreya** [comment]
@RiyaRaj28 
It seems, you didn't followed the contribution guidelines.

**Comment by RiyaRaj28** [comment]
I must have made a mistake. I couldn't attend the session.

**Comment by Debatreya** [comment]
@RiyaRaj28 
Did you followed the [contributing.md](https://github.com/Debatreya/GIT_workshop/blob/main/CONTRIBUTINIG.md)

It seems you made the contribution through Github only.

**Pull request merged**
